const games = [
  { "Название": "Grand Theft Auto IV", "Платформа": "Xbox 360", "Балл Metacritic": 98, "Год": 2008, "Студия": "Rockstar North", "Жанр": "Action-adventure" },
  { "Название": "Super Mario Galaxy", "Платформа": "Wii", "Балл Metacritic": 97, "Год": 2007, "Студия": "Nintendo EAD Tokyo", "Жанр": "Платформер" },
  { "Название": "Super Mario Galaxy 2", "Платформа": "Wii", "Балл Metacritic": 97, "Год": 2010, "Студия": "Nintendo EAD Tokyo", "Жанр": "Платформер" },
  { "Название": "The Legend of Zelda: Breath of the Wild", "Платформа": "Nintendo Switch", "Балл Metacritic": 97, "Год": 2017, "Студия": "Nintendo EPD", "Жанр": "Action-adventure" },
  { "Название": "Perfect Dark", "Платформа": "Nintendo 64", "Балл Metacritic": 97, "Год": 2000, "Студия": "Rare", "Жанр": "Шутер от первого лица" },
  { "Название": "Tony Hawk's Pro Skater 3", "Платформа": "PlayStation 2", "Балл Metacritic": 97, "Год": 2001, "Студия": "Neversoft", "Жанр": "Спорт (скейтбординг)" },
  { "Название": "Red Dead Redemption 2", "Платформа": "PlayStation 4", "Балл Metacritic": 97, "Год": 2018, "Студия": "Rockstar Studios", "Жанр": "Action-adventure" },
  { "Название": "Grand Theft Auto V", "Платформа": "PlayStation 4", "Балл Metacritic": 97, "Год": 2014, "Студия": "Rockstar North", "Жанр": "Action-adventure" },
  { "Название": "Metroid Prime", "Платформа": "GameCube", "Балл Metacritic": 97, "Год": 2002, "Студия": "Retro Studios", "Жанр": "Приключенческая игра от первого лица" },
  { "Название": "Grand Theft Auto III", "Платформа": "PlayStation 2", "Балл Metacritic": 97, "Год": 2001, "Студия": "DMA Design", "Жанр": "Action-adventure" },
  { "Название": "Super Mario Odyssey", "Платформа": "Nintendo Switch", "Балл Metacritic": 97, "Год": 2017, "Студия": "Nintendo EPD", "Жанр": "Платформер" },
  { "Название": "Halo: Combat Evolved", "Платформа": "Xbox", "Балл Metacritic": 97, "Год": 2001, "Студия": "Bungie", "Жанр": "Шутер от первого лица" },
  { "Название": "NFL 2K1", "Платформа": "Dreamcast", "Балл Metacritic": 97, "Год": 2000, "Студия": "Visual Concepts", "Жанр": "Спорт (американский футбол)" },
  { "Название": "Half-Life 2", "Платформа": "PC", "Балл Metacritic": 96, "Год": 2004, "Студия": "Valve", "Жанр": "Научно-фантастический шутер от первого лица" },
  { "Название": "BioShock", "Платформа": "Xbox 360", "Балл Metacritic": 96, "Год": 2007, "Студия": "2K Boston / 2K Australia", "Жанр": "Шутер от первого лица с элементами RPG" },
  { "Название": "Uncharted 2: Among Thieves", "Платформа": "PlayStation 3", "Балл Metacritic": 96, "Год": 2009, "Студия": "Naughty Dog", "Жанр": "Приключенческий боевик; шутер от третьего лица" },
  { "Название": "Resident Evil 4", "Платформа": "GameCube", "Балл Metacritic": 96, "Год": 2005, "Студия": "Capcom Production Studio 4", "Жанр": "Survival horror; action-adventure" },
  { "Название": "Baldur's Gate 3", "Платформа": "PC", "Балл Metacritic": 96, "Год": 2023, "Студия": "Larian Studios", "Жанр": "Ролевая игра" },
  { "Название": "The Orange Box", "Платформа": "Xbox 360", "Балл Metacritic": 96, "Год": 2007, "Студия": "Valve", "Жанр": "Сборник (шутер; головоломка)" },
  { "Название": "Mass Effect 2", "Платформа": "Xbox 360", "Балл Metacritic": 96, "Год": 2010, "Студия": "BioWare", "Жанр": "Action RPG; шутер от третьего лица" },
  { "Название": "The House in Fata Morgana: Dreams of the Revenants Edition", "Платформа": "Nintendo Switch", "Балл Metacritic": 96, "Год": 2021, "Студия": "Novectacle", "Жанр": "Визуальный роман" },
  { "Название": "Elden Ring", "Платформа": "PlayStation 5", "Балл Metacritic": 96, "Год": 2022, "Студия": "FromSoftware", "Жанр": "Action RPG" },
  { "Название": "The Elder Scrolls V: Skyrim", "Платформа": "Xbox 360", "Балл Metacritic": 96, "Год": 2011, "Студия": "Bethesda Game Studios", "Жанр": "Action RPG; открытый мир" },
  { "Название": "The Legend of Zelda: Tears of the Kingdom", "Платформа": "Nintendo Switch", "Балл Metacritic": 96, "Год": 2023, "Студия": "Nintendo EPD", "Жанр": "Action-adventure" },
  { "Название": "The Legend of Zelda: The Wind Waker", "Платформа": "GameCube", "Балл Metacritic": 96, "Год": 2003, "Студия": "Nintendo EAD", "Жанр": "Action-adventure" },
  { "Название": "Metal Gear Solid 2: Sons of Liberty", "Платформа": "PlayStation 2", "Балл Metacritic": 96, "Год": 2001, "Студия": "Konami Computer Entertainment Japan", "Жанр": "Стелс-экшн" },
  { "Название": "Grand Theft Auto Double Pack", "Платформа": "Xbox", "Балл Metacritic": 96, "Год": 2003, "Студия": "Rockstar North", "Жанр": "Сборник (action-adventure)" },
  { "Название": "Portal: Companion Collection", "Платформа": "Nintendo Switch", "Балл Metacritic": 95, "Год": 2022, "Студия": "Valve (порт: Nvidia Lightspeed)", "Жанр": "Головоломка-платформер (сборник)" },
  { "Название": "Baldur's Gate II: Shadows of Amn", "Платформа": "PC", "Балл Metacritic": 95, "Год": 2000, "Студия": "BioWare", "Жанр": "Ролевая игра" },
  { "Название": "Grand Theft Auto: San Andreas", "Платформа": "PlayStation 2", "Балл Metacritic": 95, "Год": 2004, "Студия": "Rockstar North", "Жанр": "Action-adventure" },
  { "Название": "Grand Theft Auto: Vice City", "Платформа": "PlayStation 2", "Балл Metacritic": 95, "Год": 2002, "Студия": "Rockstar North", "Жанр": "Action-adventure" },
  { "Название": "LittleBigPlanet", "Платформа": "PlayStation 3", "Балл Metacritic": 95, "Год": 2008, "Студия": "Media Molecule", "Жанр": "Платформер; конструктор уровней" },
  { "Название": "The Legend of Zelda Collector's Edition", "Платформа": "GameCube", "Балл Metacritic": 95, "Год": 2003, "Студия": "Nintendo", "Жанр": "Сборник (action-adventure)" },
  { "Название": "The Legend of Zelda: Tears of the Kingdom — Switch 2 Edition", "Платформа": "Nintendo Switch 2", "Балл Metacritic": 95, "Год": 2025, "Студия": "Nintendo EPD", "Жанр": "Action-adventure" },
  { "Название": "Gran Turismo 3: A-Spec", "Платформа": "PlayStation 2", "Балл Metacritic": 95, "Год": 2001, "Студия": "Polyphony Digital", "Жанр": "Гоночный симулятор" },
  { "Название": "Halo 2", "Платформа": "Xbox", "Балл Metacritic": 95, "Год": 2004, "Студия": "Bungie", "Жанр": "Шутер от первого лица" },
  { "Название": "The Legend of Zelda: A Link to the Past / Four Swords", "Платформа": "Game Boy Advance", "Балл Metacritic": 95, "Год": 2002, "Студия": "Nintendo EAD / Capcom", "Жанр": "Action-adventure" },
  { "Название": "The Legend of Zelda: Majora's Mask", "Платформа": "Nintendo 64", "Балл Metacritic": 95, "Год": 2000, "Студия": "Nintendo EAD", "Жанр": "Action-adventure" },
  { "Название": "The Last of Us", "Платформа": "PlayStation 3", "Балл Metacritic": 95, "Год": 2013, "Студия": "Naughty Dog", "Жанр": "Action-adventure; survival" },
  { "Название": "The Legend of Zelda: Breath of the Wild — Switch 2 Edition", "Платформа": "Nintendo Switch 2", "Балл Metacritic": 95, "Год": 2025, "Студия": "Nintendo EPD", "Жанр": "Action-adventure" },
  { "Название": "The Legend of Zelda: Twilight Princess", "Платформа": "GameCube", "Балл Metacritic": 95, "Год": 2006, "Студия": "Nintendo EAD", "Жанр": "Action-adventure" },
  { "Название": "Madden NFL 2003", "Платформа": "PlayStation 2", "Балл Metacritic": 95, "Год": 2002, "Студия": "EA Tiburon", "Жанр": "Спорт (американский футбол)" },
  { "Название": "Persona 5 Royal", "Платформа": "PlayStation 4", "Балл Metacritic": 95, "Год": 2020, "Студия": "Atlus", "Жанр": "JRPG" },
  { "Название": "The Last of Us Remastered", "Платформа": "PlayStation 4", "Балл Metacritic": 95, "Год": 2014, "Студия": "Naughty Dog", "Жанр": "Action-adventure; survival" },
  { "Название": "Red Dead Redemption", "Платформа": "Xbox 360", "Балл Metacritic": 95, "Год": 2010, "Студия": "Rockstar San Diego", "Жанр": "Action-adventure" },
  { "Название": "Portal 2", "Платформа": "PlayStation 3", "Балл Metacritic": 95, "Год": 2011, "Студия": "Valve", "Жанр": "Головоломка-платформер" },
  { "Название": "Astro Bot", "Платформа": "PlayStation 5", "Балл Metacritic": 94, "Год": 2024, "Студия": "Team Asobi (SIE)", "Жанр": "Платформер" },
  { "Название": "Final Fantasy IX", "Платформа": "PlayStation", "Балл Metacritic": 94, "Год": 2000, "Студия": "Square", "Жанр": "JRPG" },
  { "Название": "God of War (2018)", "Платформа": "PlayStation 4", "Балл Metacritic": 94, "Год": 2018, "Студия": "Santa Monica Studio", "Жанр": "Action-adventure" },
  { "Название": "Tony Hawk's Pro Skater 4", "Платформа": "PlayStation 2", "Балл Metacritic": 94, "Год": 2002, "Студия": "Neversoft", "Жанр": "Спорт (скейтбординг)" }
];

export default games;
